### ISSUE TITLE
No module named 'PyQt5.QtSerialPort'

### ISSUE THREAD

**Issue by freekvh** [tasmota/tasmotizer#18] opened 2020-01-18 19:04 UTC
Hi,

I followed install instructions, but cloning the repo and running `python3 tasmotizer.py` ends in:

```
Traceback (most recent call last):
  File "tasmotizer.py", line 15, in <module>
    from PyQt5.QtSerialPort import QSerialPortInfo, QSerialPort
ModuleNotFoundError: No module named 'PyQt5.QtSerialPort'
```

I can import PyQt5 in a python3 console, but running:

```
from PyQt5.QtSerialPort import QSerialPortInfo, QSerialPort
```

Results in the same error... PyQt5 does not seem to contain QtSerialPort.

**Comment by jziolkowski** [comment] 2020-01-19 13:55
Duplicate of #12

**Closed by jziolkowski** 2020-01-19 13:55 UTC
