### ISSUE TITLE
Windows 1.1a GUI Quits before flashing

### ISSUE THREAD

**Issue by richard-scott** [tasmota/tasmotizer#39] opened 2020-05-01 14:34 UTC
I have tried to use the Windows 1.1a EXE and as soon as I click on the "release" or "development" selectors in the middle the app quits. I want to be able to select from the dropdown the release to install but the app just quits.

I have tried both the x86 one, and the other.

**Comment by richard-scott** [comment] 2020-05-04 19:17
Odd, it's working today.... seems to be network related.

To test that theory, I've just disconnected from the Internet, loaded the app and it quit when trying to select a firmware release to install.

**Comment by richard-scott** [comment] 2020-05-05 11:40
I get this error in the console from the latest build form the develop branch:

![2020-05-05 12_22_20-Window](https://user-images.githubusercontent.com/5149834/81060859-3829f300-8ecb-11ea-9c5c-263e45a16436.png)

The only way I've been able to stop it quitting is to do the following:

![2020-05-05 12_39_15-Window](https://user-images.githubusercontent.com/5149834/81062208-7a543400-8ecd-11ea-8af2-1480f290920e.png)

**Comment by golddragon007** [comment] 2020-05-20 17:28
It seems for me from the error like the decoder doesn't get JSON in time. With another project I had a problem because they set the timeout for 2 seconds and I've needed appr. 4... maybe similar here too, however for me it's perfectly working the selectors.

**Comment by richard-scott** [comment] 2020-05-20 21:13
@golddragon007 yes, I agree the timeout may be too low. To test you could disable Internet access on your computer by switching off WiFi, or disconnecting the network cable. The lack of a JSON response from the Internet isn't handled gracefully.

**Comment by golddragon007** [comment] 2020-05-20 23:43
As I've dug into this now a bit, I just realized, I don't know python well :D. Well, I see there's a lot of places where I can improve this (after now I've flashed 15 devices in a row), just the knowledge missing :(. Besides that, I've fount the location I can't put there anything because the library doesn't support such stuff (like timeout parameter), you need your implementation for that. Soooo... I'm dead. What I've fount it waits around 2 seconds and then it will exit (at least the comment says that).

**Comment by richard-scott** [comment] 2020-05-21 09:11
No worries @golddragon007 I'm going to have a look over the weekend. I know Python a bit, so may be able to fix it.

**Comment by andykams** [comment] 2020-06-21 01:37
I think I am having a similar issue too . 
When I select backup firmware and flash the device I get the progress bar stuck on writing done. 
![image](https://user-images.githubusercontent.com/65895397/85214780-d53ad100-b33d-11ea-81af-2aca47f6e786.png)

Then errors out:
![image](https://user-images.githubusercontent.com/65895397/85214818-306cc380-b33e-11ea-9d6c-acfe011977ad.png)

If I do not check "Back up original firmware" it completes flashing fine.

**Comment by golddragon007** [comment] 2020-06-22 07:39
Ahh, you get an error message? After how much time? Because I think I've waited for half a min and nothing happened. And every time, when it's in this state and I disconnecting the device, it's crashing the application.

**Comment by mrekin** [comment] 2020-07-02 07:59
So the same thing (GUI close) happens when com port is busy by other app\terminal.

**Comment by andykams** [comment] 2020-07-02 19:15
It was about 2-3 mins after I get an error. That was 2 out of 5 times and rest I did not get a error.

**Comment by Mark-Muc** [comment] 2020-07-11 09:24
same issue here by selecting "development", waiting cursor show up for 2 sec and then it "quits" itself
"release" 8.3.1 works as expected

**Comment by Morphy99** [comment] 2020-08-14 13:12
> same issue here by selecting "development", waiting cursor show up for 2 sec and then it "quits" itself
> "release" 8.3.1 works as expected

Have you got a link for 8.3.1 please? I'm trying to use this to backup an ESP8266 and without using ESPTOOL the only way on windowz

**Comment by richard-scott** [comment] 2020-08-14 13:15
They are on Github:

https://github.com/arendst/Tasmota/releases/tag/v8.3.1

**Comment by Morphy99** [comment] 2020-08-14 13:44
> They are on Github:
> 
> https://github.com/arendst/Tasmota/releases/tag/v8.3.1

Sorry, I thought it was an earlier version of Tasmotizer! I'm not backing up tasmota, using it to backup WLED and ESPHome. Guess I'll have to boot into Linux live and use esptool command line to backup the ESP for now until this is fixed.

**Comment by theetron** [comment] 2020-08-27 12:38
Sam issue here, after selecting release or develop, application crashes. What can be done to fix this?

**Comment by PreferHardware** [comment] 2020-08-27 14:56
Same here: open Tasmotizer on Windows and Linux (Mint) and it crashes as soon as Release or Development is selected. On Windows it just closes and on Linux I get:

Traceback (most recent call last):
  File "tasmotizer.py", line 557, in setBinMode
    self.processReleaseInfo()
  File "tasmotizer.py", line 577, in processReleaseInfo
    reply = json.loads(str(self.release_data, 'utf8'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Mark-Muc** [comment] 2020-08-28 06:54
same by me .. now it "chrashes" also selecting release .. I guess the URL's to release and Developemd  has changed ..

**Comment by PreferHardware** [comment] 2020-08-28 09:06
In https://tasmota.github.io/docs/ and elsewhere the download location for Tasmota binaries is linked to http://thehackbox.org/tasmota/release/. This is no longer accessible. On reflection, I wonder if this is what is causing Tasmotize to fail.

As a workaround, I used the NodeMCU Py-Flasher from https://github.com/marcelstoer/nodemcu-pyflasher/releases and manually downloaded the binary I needed from https://github.com/arendst/Tasmota/releases/tag/v8.4.0. This worked well for me.

**Comment by Jason2866** [comment] 2020-08-29 17:37
Can you try latest release version?

**Comment by PreferHardware** [comment] 2020-08-29 17:51
Hi Jason, I've just tried 1.1c and it works as designed although I've not checked the version it actually downloads, but since you've changed the source to the OTA repo I'm assuming it is the latest release version. Well done, so quick, thank you. Resolved.

**Comment by discip** [comment] 2020-08-29 20:32
@Jason2866
Good evening sir,
**thank you** for the almost *immediate* response!
But every single release beginning with ***`tasmotizer-1.1a.exe`*** is behaving the same when either 'Release' or 'Development' is selected: It just closes.
The only working one is the ***`tasmotizer-1.0.exe`***.

I am on latest **Win10** *(64bit, if that matters)*.

regards

**Comment by PreferHardware** [comment] 2020-08-29 20:43
1.1c has just worked for me.

**Comment by discip** [comment] 2020-08-29 20:50
@PreferHardware 
Good evening sir,
may I please get to know, what you are running?

**Comment by PreferHardware** [comment] 2020-08-29 20:57
W10-64. Just checked again: I get the release/development drop-down lists, where 1.1a quit.

**Comment by discip** [comment] 2020-08-29 21:03
Strange!
Have you plugged in any any 'flash-able' device?

**Comment by PreferHardware** [comment] 2020-08-29 21:13
No, the first time. Yes, the second. It works either way.

**Comment by discip** [comment] 2020-08-29 21:28
That gives me a hard time, because there seems to be no way for me to get it to work.
I re-downloaded it at least once more and even tried your link, but both ways without any luck.
The ***1.0*** however works as expected.

**Comment by Jason2866** [comment] 2020-08-29 21:41
@discip Have you checked Backup or Erase? Try with uncheck both.

**Comment by theetron** [comment] 2020-08-30 08:22
> Same issue here, after selecting release or develop, application crashes. What can be done to fix this?

Version 1.1a is working now, and the 1.1c is also working.

**Comment by discip** [comment] 2020-08-31 16:35
@Jason2866 
I have tried every possible combination with and without a device being plugged in.
It just keeps closing. 🤷‍♂️😵

By the way: Backup saves only 1MB. I have used a Shelly2.5 and its backup should be 2MB.

thanks
regards

**Comment by Jason2866** [comment] 2020-08-31 16:45
The new version (no release date yet) will have a option to do different backup sizes

**Comment by discip** [comment] 2020-09-01 15:18
@Jason2866
*Sorry for off topic content.*
Will it detect the flash size by itself, like "[NodeMCU-PyFlasher-4.0](https://github.com/marcelstoer/nodemcu-pyflasher/releases)" does?
If you check **`Erase before flashing`** does it erase only 1MB or according to the actual flash size of the attached device?

**Comment by discip** [comment] 2020-09-01 15:36
@Jason2866
Now the lastest Version ***1.1c*** works as intended.
All I did was executing different flashing software like:

1. **ESP.Easy.Flasher.exe** & its updater ***Update.exe***
2. **NodeMCU-PyFlasher-4.0-x64.exe**
3. **Tasmota-PyFlasher-1.0.exe**

Just in case someone stumbles across the issue I had as well.
Maybe somebody is able to figure out, why it suddenly started to work, after I did what is mentioned above. Maybe the ***Updater.exe*** did the trick. 🤷‍♂️

**Comment by Jason2866** [comment] 2020-09-01 17:30
Flash erase does erase the whold flash. It does not matter if it is 1M 2M 4M or 16M

**Closed by Jason2866** 2020-09-01 17:30 UTC

**Comment by discip** [comment] 2020-09-01 20:02
@Jason2866
## Thank you for you consistency in replying. Please keep it this way. 👍😀
I hope yo did not get me wrong, about me, being some kind of taciturn in terms of saying THANK YOU for your effort, while mentioning the issues I had.
It was due to the fact that there are **so many issues opened** and it seemed the **developer dropped this project**, than, all of a sudden, YOU popped out of nowhere (I did not know until recently, that you were involved in developing this besides @jziolkowski.), so I thought HE (meaning you) might be the one, being able to solve all the grievances, and I jumped just right at you. 😔
# 👍THANK YOU 👍

**Comment by Jason2866** [comment] 2020-09-01 20:27
@jziolkowski did not drop support of his program Tasmotizer. 
In everyones life are changes... Priorities have to or need to be changed.
Keep in mind it is done in free time and no one pays for.
Stay tuned. He is working on features requested here. It is done when it is done 😎

**Comment by discip** [comment] 2020-09-01 20:59
No no, please do not get me wrong. 😱
I did not say @jziolkowski dropped this project. But it rather seemed, that this was the fact.

I do appreciate all the people, who participate in opensource and do beautiful things like ***"Tasmotizer"*** .
And I, of course understand, that people have higher priorities than programming software.

So, I am willing to wait until it is finished.

**Comment by jziolkowski** [comment] 2020-09-01 21:39
Thanks for all the kind words ;) I completely agree that the project might have looked as abandoned, but it's really not. As I write this, there are new features being tested (available under 1.1d branch) to be released this week. And indeed @Jason2866 deserves the praise, as his stepping up to fix the OTA server issue gave me the needed kick to get back to Tasmotizer.

**Comment by discip** [comment] 2020-09-01 22:19
@jziolkowski
Oh no. I am the one, who should **thank you**, for developing such beautiful piece of software!
That's good news! But please do not push yourself and take your time.
I am used to go with these sayings: ***"A good thing takes time!"*** and ***"Good things come to those who wait!"***.
